### ISSUE TITLE
You're missing some i3 scripts, wallpapers etc

### ISSUE THREAD

**Issue by victornor** [theglitchh/dotfiles#2]

**Comment by TheSerphh** [comment]
i actually have everything pushed here
you can refer to this video which i've uploaded on youtube
it shows how i have the setup up and running , it was made for the nord theme which is the master branch but if you want the gruvbox just replace the branch when cloning the dotfiles 

video link : https://youtu.be/2KgxMfgJR_k

**Comment by TheSerphh** [comment]
did a fresh install , apparently some of the dotfiles for left off , i will try to add them within this week

**Comment by TheSerphh** [comment]
@victornor i have moved on to new setup actually , its gruvbox but its now more blueish , still uses the gruvbox color scheme though, but i am unable to recover the conky theme , i still have the music visualiser config though , if you want it i can just add that to the dotfiles on gruvbox-thefallnn
![Screenshot from 2022-12-05 21-52-56](https://user-images.githubusercontent.com/103628008/205688932-8b8b0914-090d-4579-91c1-73d4e7777712.png)
